import type { Locale } from "../types";

type CopyValue = string | ((value: string) => string);
type CopyTree = { [key: string]: CopyValue | CopyTree };

const UI_COPY: Record<Locale, CopyTree> = {
  en: {
    brand: "MeshCraft",
    toolbar: {
      undo: "Undo",
      redo: "Redo",
      new: "New",
      open: "Open",
      save: "Save",
      import: "Import",
      exportGlb: "Export GLB",
      saved: "Saved",
      unsaved: "Unsaved",
      unloadImportedAsset: "Unload imported asset",
      language: "Language",
      theme: "Theme",
      dark: "Dark",
      light: "Light",
    },
    mode: {
      object: "Object",
      material: "Material",
      render: "Render",
      analyze: "Analyze",
    },
    app: {
      perspective: "Perspective",
      selection: "Selection",
      importAsset: "Import Asset",
      dragHint: "drag to orbit · scroll to zoom · right drag to pan",
    },
    scenePanel: {
      scene: "Scene",
      assets: "Assets",
      materials: "Materials",
      outliner: "Outliner",
      searchNodes: "Search nodes",
      noNodesMatch: (query: string) => `No nodes match "${query}".`,
      meshes: "meshes",
      materialsSummary: "materials",
      textures: "textures",
    },
    inspector: {
      inspector: "Inspector",
      analyze: "Analyze",
      transform: "Transform",
      material: "Material",
      textures: "Textures",
      display: "Display",
      performance: "Performance",
      selection: "Selection",
      position: "Position",
      rotation: "Rotation",
      scale: "Scale",
      transformHelp:
        "Transform editing is available for mesh objects and imported scene roots.",
      materialHelp:
        "Select a procedural mesh or material slot to edit bound material values.",
      baseColor: "Base Color",
      metalness: "Metalness",
      roughness: "Roughness",
      emission: "Emission",
      opacity: "Opacity",
      textureHelp: "Select a bound material to inspect imported texture slots.",
      noTextureMaps: "No texture maps are bound on the selected material.",
      previewUnavailable: "Preview unavailable for this texture source.",
      override: "Override",
      replace: "Replace",
      reset: "Reset",
      shading: "Shading",
      shaded: "Shaded",
      wire: "Wire",
      matcap: "Matcap",
      normals: "Normals",
      wireframeOverlay: "Wireframe Overlay",
      shadows: "Shadows",
      grid: "Grid",
      transformGizmo: "Transform Gizmo",
      scatterField: "Scatter Field",
      hologramScan: "Hologram Scan",
      postFx: "Post FX",
      lodPreview: "LOD Preview",
      autoRotate: "Auto Rotate",
      triangles: "Triangles",
      instances: "Instances",
      drawCalls: "Draw Calls",
      gpuMemory: "GPU Memory",
      decode: "Decode",
      target: "Target",
      stable: "Stable",
      warm: "Warm",
      selectedNode: "Selected Node",
      materialSlot: "Material Slot",
      importedUnbound: "Imported / unbound",
      captureViewport: "Capture Viewport",
      captureFormat: "Format",
      captureSource: "Source",
      captureFx: "Post FX",
      captureShadows: "Shadows",
      proceduralScene: "Procedural Scene",
      enabled: "Enabled",
      disabled: "Disabled",
      totalNodes: "Total Nodes",
      groups: "Groups",
      meshes: "Meshes",
      materialsCount: "Materials",
      texturesCount: "Textures",
      lights: "Lights",
      cameras: "Cameras",
      sceneTriangles: "Scene Tris",
      nodeKind: "Node Kind",
      childNodes: "Child Nodes",
      selectionTriangles: "Selection Tris",
      scenePath: "Scene Path",
      unresolved: "Unresolved",
    },
    status: {
      fps: "FPS",
      tris: "Tris",
      instances: "Instances",
      drawCalls: "Draw Calls",
      gpuMem: "GPU Mem",
      decode: "Decode",
      selection: "Sel",
    },
    importStatus: {
      loading: (assetName: string) => `Loading ${assetName}`,
      loaded: (assetName: string) => `Loaded ${assetName}`,
      failed: "Import failed",
      ready: "Ready",
      invalidAsset: "Only .glb and .gltf files are supported",
      invalidProject: "Invalid MeshCraft project file",
      invalidTexture: "Only .png, .jpg, .jpeg, and .webp textures are supported",
      readImportFailed: "Failed to read import file",
    },
  },
  "zh-CN": {
    brand: "MeshCraft",
    toolbar: {
      undo: "撤销",
      redo: "重做",
      new: "新建",
      open: "打开",
      save: "保存",
      import: "导入",
      exportGlb: "导出 GLB",
      saved: "已保存",
      unsaved: "未保存",
      unloadImportedAsset: "卸载已导入资产",
      language: "语言",
      theme: "主题",
      dark: "暗色",
      light: "亮色",
    },
    mode: {
      object: "对象",
      material: "材质",
      render: "渲染",
      analyze: "分析",
    },
    app: {
      perspective: "透视视图",
      selection: "当前选择",
      importAsset: "导入资产",
      dragHint: "拖拽旋转 · 滚轮缩放 · 右键拖拽平移",
    },
    scenePanel: {
      scene: "场景",
      assets: "资源",
      materials: "材质",
      outliner: "场景树",
      searchNodes: "搜索节点",
      noNodesMatch: (query: string) => `没有匹配“${query}”的节点。`,
      meshes: "网格",
      materialsSummary: "材质",
      textures: "贴图",
    },
    inspector: {
      inspector: "检查器",
      analyze: "分析",
      transform: "变换",
      material: "材质",
      textures: "贴图",
      display: "显示",
      performance: "性能",
      selection: "选择",
      position: "位置",
      rotation: "旋转",
      scale: "缩放",
      transformHelp: "只有网格对象和导入场景根节点支持变换编辑。",
      materialHelp: "请选择程序化网格或材质槽位以编辑绑定材质。",
      baseColor: "基础颜色",
      metalness: "金属度",
      roughness: "粗糙度",
      emission: "自发光",
      opacity: "透明度",
      textureHelp: "请选择已绑定的材质以查看导入贴图槽位。",
      noTextureMaps: "当前选中材质没有绑定贴图通道。",
      previewUnavailable: "当前贴图源暂时无法预览。",
      override: "已覆盖",
      replace: "替换",
      reset: "重置",
      shading: "着色",
      shaded: "实体",
      wire: "线框",
      matcap: "材质捕捉",
      normals: "法线",
      wireframeOverlay: "线框叠加",
      shadows: "阴影",
      grid: "网格",
      transformGizmo: "变换手柄",
      scatterField: "实例散布",
      hologramScan: "全息扫描",
      postFx: "后期效果",
      lodPreview: "LOD 预览",
      autoRotate: "自动旋转",
      triangles: "三角面",
      instances: "实例数",
      drawCalls: "Draw Calls",
      gpuMemory: "GPU 内存",
      decode: "解码",
      target: "状态",
      stable: "稳定",
      warm: "偏高",
      selectedNode: "当前节点",
      materialSlot: "材质槽位",
      importedUnbound: "导入资产 / 未绑定",
      captureViewport: "截取视口",
      captureFormat: "格式",
      captureSource: "来源",
      captureFx: "后期效果",
      captureShadows: "阴影",
      proceduralScene: "程序化场景",
      enabled: "开启",
      disabled: "关闭",
      totalNodes: "总节点数",
      groups: "分组",
      meshes: "网格",
      materialsCount: "材质数",
      texturesCount: "贴图数",
      lights: "灯光",
      cameras: "相机",
      sceneTriangles: "场景面数",
      nodeKind: "节点类型",
      childNodes: "子节点数",
      selectionTriangles: "选中面数",
      scenePath: "场景路径",
      unresolved: "未解析",
    },
    status: {
      fps: "FPS",
      tris: "面数",
      instances: "实例",
      drawCalls: "Draw Calls",
      gpuMem: "GPU 内存",
      decode: "解码",
      selection: "选择",
    },
    importStatus: {
      loading: (assetName: string) => `正在加载 ${assetName}`,
      loaded: (assetName: string) => `已加载 ${assetName}`,
      failed: "导入失败",
      ready: "就绪",
      invalidAsset: "仅支持 .glb 和 .gltf 文件",
      invalidProject: "无效的 MeshCraft 项目文件",
      invalidTexture: "仅支持 .png、.jpg、.jpeg 和 .webp 贴图",
      readImportFailed: "读取导入文件失败",
    },
  },
};

export function getCopy(locale: Locale, path: string, arg?: string): string {
  const resolved = path.split(".").reduce<CopyValue | CopyTree | undefined>((value, key) => {
    if (!value || typeof value === "string" || typeof value === "function") {
      return value;
    }

    return value[key];
  }, UI_COPY[locale]);

  if (typeof resolved === "function") {
    return resolved(arg ?? "");
  }

  return typeof resolved === "string" ? resolved : path;
}
